application: app-id
version: 1
runtime: python27
api_version: 1
threadsafe: false

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*

default_expiration: "7d"

handlers:
- url: /static
  static_dir: static

- url: /js
  static_dir: javascript

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
  mime_type: image/x-icon


- url: /_ah/mail/post@.*
  script: main.app
  login: admin

- url: /admin/.*
  script: main.app
  login: admin

- url: /*
  script: main.app

- url: /tests/.*
  script: aeta.main.APP
  login: admin
  
- url: /.*
  script: main.app
  login: required

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

builtins:
- deferred: on
- remote_api: on
- appstats: on

inbound_services:
- mail
