application: box-dinoia
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$

handlers:
- url: /static
  static_dir: static

- url: /img
  static_dir: static  

- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico
  mime_type: image/x-icon

- url: /*
  script: home.app

- url: /.*
  script: home.app
  login: required

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

builtins:
- deferred: on