application: app-id
version: 1
runtime: python27
api_version: 1
threadsafe: false

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: /favicon.ico
  upload: /favicon\.ico
  mime_type: image/x-icon

- url: /_ah/mail/post@.*
  script: home.app
  login: admin

- url: /adm/.*
  script: home.app
  login: admin

- url: /*
  script: home.app

- url: /.*
  script: home.app
  login: required

libraries:
- name: jinja2
  version: latest
- name: webapp2
  version: latest

builtins:
- deferred: on
- remote_api: on
- appstats: on

inbound_services:
- mail
